project:
  type: website
  output-dir: docs

website:
  title: "CognitiveDiscoveries"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/toobarahimnia
      - icon: linkedin
        href: https://linkedin.com/in/tooba-rahimnia
      - icon: envelope
        href: mailto:trahimnia@gmail.com
      
format:
  html:
    theme: cosmo 
    css: styles.css
    code-line-numbers: true
    highlight-style: gruvbox-dark      

editor: visual

